name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"

    - name: Run linting
      run: |
        ruff check .
        black --check .
        mypy src

    - name: Run tests
      run: |
        pytest src/tests --cov=streamlit_template

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Streamlit Cloud
      run: |
        echo "Deploy to Streamlit Cloud via GitHub integration"
